[package]
name = "patternfly-yew-quickstart"
version = "0.1.0"
authors = ["Jens Reimann <jreimann@redhat.com>"]
edition = "2018"
license = "Apache-2.0"
readme = "README.md"
description = "A quickstart project for using Patternfly with Yew Stack"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
wasm-logger = "0.2"

yew = "0.17"
yew-router = "0.14"

chrono = { version = "0.4", features = ["wasmbind"] }

patternfly-yew = "0.0.25"

strum = "0.19"

log = "0.4"

[patch.crates-io]
#patternfly-yew = { path = "../patternfly-yew" }
